### ISSUE TITLE
No such file or directory - systemctl on ubuntu older than 15.04

### ISSUE THREAD

**Issue by joshzitting** [xhost-cookbooks/system#49]
https://github.com/xhost-cookbooks/system/blob/master/providers/hostname.rb#L312

```ruby
# for systemd systems with systemd-hostnamed unit
  service 'systemd-hostnamed' do
    provider ::Chef::Provider::Service::Systemd
    only_if 'systemctl is-enabled systemd-hostnamed'
    action :nothing
  end
```
is failing chef runs that are on ubutnu older than 15.04. 
the only if needs to be something like 
``` only_if 'which systemctl && systemctl is-enabled systemd-hostnamed'```

we are using this on 14.04 and the recommendation above works.

**Comment by flaccid** [comment]
Can you paste the chef output with the error included?

**Comment by joshzitting** [comment]
```ruby
10.129.100.100     * execute[run hostname] action run (skipped due to not_if)
10.129.100.100     * execute[ensure hostname sync'd] action run (skipped due to not_if)
10.129.100.100     * execute[set rightscale server hostname tag] action run (skipped due to only_if)
10.129.100.100     * service[systemd-hostnamed] action restart
10.129.100.100
10.129.100.100       ================================================================================
10.129.100.100       Error executing action `restart` on resource 'service[systemd-hostnamed]'
10.129.100.100       ================================================================================
10.129.100.100
10.129.100.100       Errno::ENOENT
10.129.100.100       -------------
10.129.100.100       No such file or directory - systemctl
10.129.100.100
10.129.100.100       Cookbook Trace:
10.129.100.100       ---------------
10.129.100.100       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
10.129.100.100       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:136:in `run_delayed_notification'
10.129.100.100       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:124:in `block in run_delayed_notifications'
10.129.100.100       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:123:in `each'
10.129.100.100       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:123:in `run_delayed_notifications'
10.129.100.100       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:113:in `converge'
10.129.100.100       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
10.129.100.100       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
10.129.100.100       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
10.129.100.100       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
10.129.100.100       /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
10.129.100.100
10.129.100.100       Resource Declaration:
10.129.100.100       ---------------------
10.129.100.100       # In /var/chef/cache/cookbooks/system/providers/hostname.rb
10.129.100.100
10.129.100.100       310:   service 'systemd-hostnamed' do
10.129.100.100       311:     provider ::Chef::Provider::Service::Systemd
10.129.100.100       312:     only_if 'systemctl is-enabled systemd-hostnamed'
10.129.100.100       313:     action :nothing
10.129.100.100       314:   end
10.129.100.100       315:
10.129.100.100
10.129.100.100       Compiled Resource:
10.129.100.100       ------------------
10.129.100.100       # Declared in /var/chef/cache/cookbooks/system/providers/hostname.rb:310:in `block in class_from_file'
10.129.100.100
10.129.100.100       service("systemd-hostnamed") do
10.129.100.100         provider Chef::Provider::Service::Systemd
10.129.100.100         action [:nothing]
10.129.100.100         supports {:restart=>nil, :reload=>nil, :status=>nil}
10.129.100.100         retries 0
10.129.100.100         retry_delay 2
10.129.100.100         default_guard_interpreter :default
10.129.100.100         service_name "systemd-hostnamed"
10.129.100.100         pattern "systemd-hostnamed"
10.129.100.100         declared_type :service
10.129.100.100         cookbook_name "system"
10.129.100.100         only_if "systemctl is-enabled systemd-hostnamed"
10.129.100.100       end
10.129.100.100
10.129.100.100       Platform:
10.129.100.100       ---------
10.129.100.100       x86_64-linux
10.129.100.100
10.129.100.100     * ruby_block[show host info] action create
10.129.100.100       - execute the ruby block show host info
10.129.100.100
10.129.100.100     ================================================================================
10.129.100.100     Error executing action `set` on resource 'system_hostname[proxy]'
10.129.100.100     ================================================================================
10.129.100.100
10.129.100.100     Errno::ENOENT
10.129.100.100     -------------
10.129.100.100     service[systemd-hostnamed] (/var/chef/cache/cookbooks/system/providers/hostname.rb line 310) had an error: Errno::ENOENT: No such file or directory - systemctl
10.129.100.100
10.129.100.100     Cookbook Trace:
10.129.100.100     ---------------
10.129.100.100     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
10.129.100.100     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:136:in `run_delayed_notification'
10.129.100.100     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:124:in `block in run_delayed_notifications'
10.129.100.100     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:123:in `each'
10.129.100.100     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:123:in `run_delayed_notifications'
10.129.100.100     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:113:in `converge'
10.129.100.100     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
10.129.100.100     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
10.129.100.100     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
10.129.100.100     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
10.129.100.100     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
10.129.100.100
10.129.100.100     Resource Declaration:
10.129.100.100     ---------------------
10.129.100.100     # In /var/chef/cache/cookbooks/system/recipes/hostname.rb
10.129.100.100
10.129.100.100      20: system_hostname node['system']['short_hostname'] do
10.129.100.100      21:   short_hostname    node['system']['short_hostname']
10.129.100.100      22:   domain_name       node['system']['domain_name']
10.129.100.100      23:   static_hosts      node['system']['static_hosts']
10.129.100.100      24:   netbios_name      node['system']['netbios_name']
10.129.100.100      25:   workgroup         node['system']['workgroup']
10.129.100.100      26:   manage_hostsfile  node['system']['manage_hostsfile']
10.129.100.100      27:   not_if            { node['virtualization'] && node['virtualization']['system'] && node['virtualization']['system'] == 'docker' }
10.129.100.100      28:
10.129.100.100      29:   # https://github.com/chef/ohai/pull/569 not yet in most used chef versions
10.129.100.100      30:   not_if            'ls /.dockerinit'
10.129.100.100      31: end
10.129.100.100
10.129.100.100     Compiled Resource:
10.129.100.100     ------------------
10.129.100.100     # Declared in /var/chef/cache/cookbooks/system/recipes/hostname.rb:20:in `from_file'
10.129.100.100
10.129.100.100     system_hostname("proxy") do
10.129.100.100       action :set
10.129.100.100       updated true
10.129.100.100       updated_by_last_action true
10.129.100.100       retries 0
10.129.100.100       retry_delay 2
10.129.100.100       default_guard_interpreter :default
10.129.100.100       declared_type :system_hostname
10.129.100.100       cookbook_name "system"
10.129.100.100       recipe_name "hostname"
10.129.100.100       short_hostname "proxy"
10.129.100.100       domain_name "any.here"
10.129.100.100       netbios_name "B95C0A7A-77AD-66B0-F5F8-AF15A4E83CA1"
10.129.100.100       workgroup "WORKGROUP"
10.129.100.100       manage_hostsfile true
10.129.100.100       not_if { #code block }
10.129.100.100       not_if "ls /.dockerinit"
10.129.100.100     end
10.129.100.100
10.129.100.100     Platform:
10.129.100.100     ---------
10.129.100.100     x86_64-linux
10.129.100.100
10.129.100.100 Recipe: cron::default
10.129.100.100   * service[cron] action restart
10.129.100.100     - restart service service[cron]
10.129.100.100
10.129.100.100 Running handlers:
10.129.100.100 [2016-09-15T18:05:02+00:00] ERROR: Running exception handlers
10.129.100.100 Running handlers complete
10.129.100.100 [2016-09-15T18:05:02+00:00] ERROR: Exception handlers complete
10.129.100.100 Chef Client failed. 76 resources updated in 01 minutes 49 seconds
10.129.100.100 [2016-09-15T18:05:02+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
10.129.100.100 [2016-09-15T18:05:02+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
10.129.100.100 [2016-09-15T18:05:02+00:00] ERROR: system_hostname[proxy] (system::hostname line 20) had an error: Errno::ENOENT: service[systemd-hostnamed] (/var/chef/cache/cookbooks/system/providers/hostname.rb line 310) had an error: Errno::ENOENT: No such file or directory - systemctl
10.129.100.100 [2016-09-15T18:05:02+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by c-hoeger** [comment]
same on RHEL6

**Comment by mengesb** [comment]
I'm getting this problem as well (Ubuntu 14.04)

**Comment by flaccid** [comment]
```
$ systemctl is-enabled systemd-hostnamed
systemctl: command not found
$ echo "$?"
127
$ type systemctl
-bash: type: systemctl: not found
$ echo "$?"
1
$ type systemctl && systemctl is-enabled systemd-hostnamed
-bash: type: systemctl: not found
$ echo "$?"
1
$ bash -c 'type -P systemctl'
$ echo "$?"
1
$ bash -c 'type -P systemctl && systemctl is-enabled systemd-hostnamed'
$ echo "$?"
1
```
I'm guessing that chef does not like a 127 (not found) but will play with a another non-zero exit code. My use of `bash -c` must also be for a reason I have forgotten. The last example is probably the right one to use.

**Comment by flaccid** [comment]
Fix now released in https://github.com/xhost-cookbooks/system/releases/tag/v0.11.2.
