### ISSUE TITLE
Error while running system timezone recipe on first boot

### ISSUE THREAD

**Issue by jpujari-cartera** [xhost-cookbooks/system#50]
We are using cloudformation for provisioning the server in AWS. As part of the AWS::CloudFormation::Init we execute a `base` role which has the system timezone recipe. The system timezone recipe halts the chef-client execution with the following connection timeout error. More than a issue, I was hoping for some insight on why this would happen. We are using centos 7 OS. Chef-Client version is 12.12.15. System cookbook version is 0.11.0.
 
 Resource Declaration:
```
2016-10-31 10:30:46,432 P2001 [INFO]    ---------------------
2016-10-31 10:30:46,432 P2001 [INFO]    # In /var/chef/cache/cookbooks/system/providers/timezone.rb
2016-10-31 10:30:46,432 P2001 [INFO]
2016-10-31 10:30:46,432 P2001 [INFO]     83:   execute "timedatectl set-timezone #{zone_file}" do
2016-10-31 10:30:46,432 P2001 [INFO]     84:     if node['system']['enable_cron'] && node['platform'] != 'mac_os_x'
2016-10-31 10:30:46,432 P2001 [INFO]     85:       notifies :restart, 'service[cron]', :immediately
2016-10-31 10:30:46,432 P2001 [INFO]     86:     end
2016-10-31 10:30:46,432 P2001 [INFO]     87:     notifies :create, 'ruby_block[verify newly-linked timezone]', :delayed
2016-10-31 10:30:46,433 P2001 [INFO]
2016-10-31 10:30:46,433 P2001 [INFO]    Compiled Resource:
2016-10-31 10:30:46,433 P2001 [INFO]    ------------------
2016-10-31 10:30:46,433 P2001 [INFO]    # Declared in /var/chef/cache/cookbooks/system/providers/timezone.rb:83:in `block in class_from_file'
2016-10-31 10:30:46,433 P2001 [INFO]
2016-10-31 10:30:46,433 P2001 [INFO]    execute("timedatectl set-timezone US/Eastern") do
2016-10-31 10:30:46,433 P2001 [INFO]      action [:run]
2016-10-31 10:30:46,433 P2001 [INFO]      retries 0
2016-10-31 10:30:46,433 P2001 [INFO]      retry_delay 2
2016-10-31 10:30:46,433 P2001 [INFO]      default_guard_interpreter :execute
2016-10-31 10:30:46,433 P2001 [INFO]      command "timedatectl set-timezone US/Eastern"
2016-10-31 10:30:46,433 P2001 [INFO]      backup 5
2016-10-31 10:30:46,433 P2001 [INFO]      returns 0
2016-10-31 10:30:46,433 P2001 [INFO]      declared_type :execute
2016-10-31 10:30:46,434 P2001 [INFO]      cookbook_name "system"
2016-10-31 10:30:46,434 P2001 [INFO]      not_if { #code block }
2016-10-31 10:30:46,434 P2001 [INFO]      only_if "bash -c 'type -P timedatectl'"
2016-10-31 10:30:46,434 P2001 [INFO]    end
2016-10-31 10:30:46,434 P2001 [INFO]
2016-10-31 10:30:46,434 P2001 [INFO]    Platform:
2016-10-31 10:30:46,434 P2001 [INFO]    ---------
2016-10-31 10:30:46,434 P2001 [INFO]    x86_64-linux
2016-10-31 10:30:46,434 P2001 [INFO]
2016-10-31 10:30:46,434 P2001 [INFO]    [2016-10-31T10:30:45-04:00] INFO: Running queued delayed notifications before re-raising exception
2016-10-31 10:30:46,434 P2001 [INFO]
2016-10-31 10:30:46,434 P2001 [INFO]    ================================================================================
2016-10-31 10:30:46,434 P2001 [INFO]    Error executing action `set` on resource 'system_timezone[US/Eastern]'
2016-10-31 10:30:46,434 P2001 [INFO]    ================================================================================
2016-10-31 10:30:46,435 P2001 [INFO]
2016-10-31 10:30:46,435 P2001 [INFO]    Mixlib::ShellOut::ShellCommandFailed
2016-10-31 10:30:46,435 P2001 [INFO]    ------------------------------------
2016-10-31 10:30:46,435 P2001 [INFO]    execute[timedatectl set-timezone US/Eastern] (/var/chef/cache/cookbooks/system/providers/timezone.rb line 83) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
2016-10-31 10:30:46,435 P2001 [INFO]    ---- Begin output of timedatectl set-timezone US/Eastern ----
2016-10-31 10:30:46,435 P2001 [INFO]    STDOUT:
2016-10-31 10:30:46,435 P2001 [INFO]    STDERR: Failed to set time zone: Connection timed out
2016-10-31 10:30:46,435 P2001 [INFO]    ---- End output of timedatectl set-timezone US/Eastern ----
2016-10-31 10:30:46,435 P2001 [INFO]    Ran timedatectl set-timezone US/Eastern returned 1
2016-10-31 10:30:46,435 P2001 [INFO]
2016-10-31 10:30:46,435 P2001 [INFO]    Cookbook Trace:
2016-10-31 10:30:46,435 P2001 [INFO]    ---------------
2016-10-31 10:30:46,435 P2001 [INFO]    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
2016-10-31 10:30:46,435 P2001 [INFO]    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
2016-10-31 10:30:46,435 P2001 [INFO]    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
2016-10-31 10:30:46,436 P2001 [INFO]    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
2016-10-31 10:30:46,436 P2001 [INFO]    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
2016-10-31 10:30:46,436 P2001 [INFO]    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
2016-10-31 10:30:46,436 P2001 [INFO]    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
2016-10-31 10:30:46,436 P2001 [INFO]    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
2016-10-31 10:30:46,436 P2001 [INFO]    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
2016-10-31 10:30:46,436 P2001 [INFO]    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
2016-10-31 10:30:46,436 P2001 [INFO]
2016-10-31 10:30:46,436 P2001 [INFO]    Resource Declaration:
2016-10-31 10:30:46,436 P2001 [INFO]    ---------------------
2016-10-31 10:30:46,436 P2001 [INFO]    # In /var/chef/cache/cookbooks/system/recipes/timezone.rb
2016-10-31 10:30:46,436 P2001 [INFO]
2016-10-31 10:30:46,436 P2001 [INFO]     20: system_timezone node['system']['timezone']
2016-10-31 10:30:46,436 P2001 [INFO]
2016-10-31 10:30:46,437 P2001 [INFO]    Compiled Resource:
2016-10-31 10:30:46,437 P2001 [INFO]    ------------------
2016-10-31 10:30:46,437 P2001 [INFO]    # Declared in /var/chef/cache/cookbooks/system/recipes/timezone.rb:20:in `from_file'
2016-10-31 10:30:46,437 P2001 [INFO]
2016-10-31 10:30:46,437 P2001 [INFO]    system_timezone("US/Eastern") do
2016-10-31 10:30:46,437 P2001 [INFO]      action :set
2016-10-31 10:30:46,437 P2001 [INFO]      updated true
2016-10-31 10:30:46,437 P2001 [INFO]      updated_by_last_action true
2016-10-31 10:30:46,437 P2001 [INFO]      retries 0
2016-10-31 10:30:46,437 P2001 [INFO]      retry_delay 2
2016-10-31 10:30:46,437 P2001 [INFO]      default_guard_interpreter :default
2016-10-31 10:30:46,437 P2001 [INFO]      declared_type :system_timezone
2016-10-31 10:30:46,437 P2001 [INFO]      cookbook_name "system"
2016-10-31 10:30:46,437 P2001 [INFO]      recipe_name "timezone"
2016-10-31 10:30:46,438 P2001 [INFO]      timezone "US/Eastern"
2016-10-31 10:30:46,438 P2001 [INFO]    end
2016-10-31 10:30:46,438 P2001 [INFO]
2016-10-31 10:30:46,438 P2001 [INFO]    Platform:
2016-10-31 10:30:46,438 P2001 [INFO]    ---------
2016-10-31 10:30:46,438 P2001 [INFO]    x86_64-linux
2016-10-31 10:30:46,438 P2001 [INFO]
2016-10-31 10:30:46,438 P2001 [INFO]    [2016-10-31T10:30:45-04:00] INFO: Running queued delayed notifications before re-raising exception
2016-10-31 10:30:46,438 P2001 [INFO]    [2016-10-31T10:30:45-04:00] ERROR: Running exception handlers
2016-10-31 10:30:46,438 P2001 [INFO]    [2016-10-31T10:30:45-04:00] ERROR: Exception handlers complete
2016-10-31 10:30:46,438 P2001 [INFO]    [2016-10-31T10:30:45-04:00] INFO: Sending resource update report (run-id: 4f80cb40-2eb6-4b87-9d15-9797b7131502)
2016-10-31 10:30:46,438 P2001 [INFO]    [2016-10-31T10:30:46-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
2016-10-31 10:30:46,438 P2001 [INFO]    [2016-10-31T10:30:46-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
2016-10-31 10:30:46,438 P2001 [INFO]    [2016-10-31T10:30:46-04:00] ERROR: system_timezone[US/Eastern] (system::timezone line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[timedatectl set-timezone US/Eastern] (/var/chef/cache/cookbooks/system/providers/timezone.rb line 83) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
2016-10-31 10:30:46,438 P2001 [INFO]    ---- Begin output of timedatectl set-timezone US/Eastern ----
2016-10-31 10:30:46,439 P2001 [INFO]    STDOUT:
2016-10-31 10:30:46,439 P2001 [INFO]    STDERR: Failed to set time zone: Connection timed out
2016-10-31 10:30:46,439 P2001 [INFO]    ---- End output of timedatectl set-timezone US/Eastern ----
2016-10-31 10:30:46,439 P2001 [INFO]    Ran timedatectl set-timezone US/Eastern returned 1
2016-10-31 10:30:46,439 P2001 [INFO]    [2016-10-31T10:30:46-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by flaccid** [comment]
There are a few possibles on google.

**Comment by dgarstang** [comment]
I'm having the same issue.

**Comment by flaccid** [comment]
This isn't an issue with the cookbook. Please take it upstream (e.g. with your distro), there is a lot on google reporting the time out when running `timedatectl set-timezone` for example, https://github.com/systemd/systemd/issues/6135.

**Comment by dgarstang** [comment]
Works fine when run from the command line. Fails when run from chef. Fail to see how that's not a chef issue.

**Comment by flaccid** [comment]
If you believe it's a chef issue that's different. Certainly no issue with this cookbook - the command is correct and works in testing.

**Comment by borgified** [comment]
as @flaccid said, the problem is upstream and i think this is the related problem:
https://access.redhat.com/solutions/2996411#comments

my current workaround is to add this to the user data:

`#cloud-config
timezone: "Europe/Amsterdam"`
