### ISSUE TITLE
Error on execute[run hostname]: No such file or directory - hostname

### ISSUE THREAD

**Issue by edupo** [xhost-cookbooks/system#59]
We are using system cookbook in our deployment and for one node we are receiving a weird error:
```
    Errno::ENOENT
    -------------
    execute[run hostname] (/var/chef/cache/cookbooks/system/providers/hostname.rb line 266) had an error: Errno::ENOENT: No such file or directory - hostname
```

We have modified the cookbook so that it calls hostname using the absolute path and we were able to make it work:

```
      269:     not_if { Mixlib::ShellOut.new('/bin/hostname -f').run_command.stdout.strip == fqdn }
```

Complete log:
```
Starting Chef Client, version 13.0.118
resolving cookbooks for run list: ["slave-database"]
Synchronizing Cookbooks:
  - etc_environment (1.0.1)
  - resolver (2.0.1)
  - seven_zip (2.0.2)
  - yum-epel (2.1.2)
  - build-essential (8.0.3)
  - yum-scl (0.2.0)
  - inifile_chef_gem (0.1.0)
  - yum (5.0.1)
  - slave-database (0.1.2)
  - selinux_policy (2.0.1)
  - chef-vault (3.0.0)
  - users (5.1.0)
  - openssl (7.1.0)
  - compat_resource (12.19.0)
  - mingw (2.0.1)
  - chef-apt-docker (2.0.2)
  - local-node (0.10.10)
  - mariadb (1.5.1)
  - ohai (5.2.0)
  - hostsfile (3.0.1)
  - windows (3.1.2)
  - apt (6.1.4)
  - cron (1.7.6)
  - docker (2.15.27)
  - system (0.11.3)
Installing Cookbook Gems:
Compiling Cookbooks...
Recipe: apt::default
  * apt_update[compile time] action periodic (up to date)
Recipe: local-node::gem_sources
  * directory[/opt/chef/embedded/etc] action create (up to date)
  Converging 53 resources
Recipe: apt::default
  * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
  * apt_update[compile time] action periodic (up to date)
  * apt_update[periodic] action periodic (up to date)
  * execute[apt-get update] action nothing (skipped due to action :nothing)
  * execute[apt-get autoremove] action nothing (skipped due to action :nothing)
  * execute[apt-get autoclean] action nothing (skipped due to action :nothing)
  * directory[/var/cache/local] action create (up to date)
  * directory[/var/cache/local/preseeding] action create (up to date)
  * template[/etc/apt/apt.conf.d/10dpkg-options] action create (up to date)
  * template[/etc/apt/apt.conf.d/10recommends] action create (up to date)
  * apt_package[apt-transport-https] action install (up to date)
Recipe: local-node::system
  * system_hostname[server1] action set
    * execute[run hostname] action run
      
      ================================================================================
      Error executing action `run` on resource 'execute[run hostname]'
      ================================================================================
      
      Errno::ENOENT
      -------------
      No such file or directory - hostname
      
      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/system/providers/hostname.rb:269:in `block (3 levels) in class_from_file'
      /var/chef/cache/cookbooks/system/providers/hostname.rb:270:in `block in class_from_file'
      
      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/system/providers/hostname.rb
      
      266:   execute 'run hostname' do
      267:     command "hostname #{fqdn}"
      268:     action :nothing
      269:     not_if { Mixlib::ShellOut.new('hostname -f').run_command.stdout.strip == fqdn }
      270:   end.run_action(:run)
      271: 
      272:   # let's not manage the entire file because its shared
      273:   ruby_block 'update network sysconfig' do
      274:     block do
      275:       fe = ::Chef::Util::FileEdit.new('/etc/sysconfig/network')
      276:       fe.search_file_replace_line(/HOSTNAME\=/, "HOSTNAME=#{fqdn}")
      277:       fe.insert_line_if_no_match(/HOSTNAME\=/, "HOSTNAME=#{fqdn}")
      278:       fe.write_file
      279:     end
      280:     only_if { ::File.exist?('/etc/sysconfig/network') }
      281:     not_if { ::File.readlines('/etc/sysconfig/network').grep(/HOSTNAME=#{fqdn}/).any? }
      282:     notifies :restart, 'service[network]', node['system']['delay_network_restart'] ? :delayed : :immediately
      283:   end
      284: 
      285:   ruby_block 'show hostnamectl' do
      286:     block do
      287:       ::Chef::Log.info('== hostnamectl ==')
      288:       ::Chef::Log.info(HostInfo.hostnamectl)
      289:     end
      290:     action :nothing
      291:     only_if "bash -c 'type -P hostnamectl'"
      292:   end
      293: 
      294:   # https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec_Configuring_Host_Names_Using_hostnamectl.html
      295:   # hostnamectl is used by other distributions too
      296:   execute 'run hostnamectl' do
      297:     command "hostnamectl set-hostname #{fqdn}"
      298:     only_if "bash -c 'type -P hostnamectl'"
      299:     not_if { Mixlib::ShellOut.new('hostname -f').run_command.stdout.strip == fqdn }
      300:     notifies :create, 'ruby_block[show hostnamectl]', :delayed
      301:   end
      302: 
      303:   # run domainname command if available
      304:   execute 'run domainname' do
      305:     command "domainname #{new_resource.domain_name}"
      306:     only_if "bash -c 'type -P domainname'"
      307:     not_if { Mixlib::ShellOut.new('domainname').run_command.stdout.strip == new_resource.domain_name }
      308:     action :nothing
      309:   end
      310: 
      311:   # for systems with cloud-init, ensure preserve hostname
      312:   # https://aws.amazon.com/premiumsupport/knowledge-center/linux-static-hostname-rhel7-centos7/
      313:   file '/etc/cloud/cloud.cfg.d/01_preserve_hostname.cfg' do
      314:     content "preserve_hostname: true\n"
      315:     only_if { ::File.exist?('/etc/cloud/cloud.cfg.d') }
      316:   end
      317: 
      318:   # for systems with nmcli (NetworkManager)
      
      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/system/providers/hostname.rb:266:in `block in class_from_file'
      
      execute("run hostname") do
        action [:nothing]
        default_guard_interpreter :execute
        command "hostname server1.localnet.com"
        backup 5
        returns 0
        user nil
        declared_type :execute
        cookbook_name "local-node"
        domain nil
        not_if { #code block }
      end
      
      System Info:
      ------------
      chef_version=13.0.118
      platform=ubuntu
      platform_version=16.04
      ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
      program_name=chef-client worker: ppid=33529;start=09:08:12;
      executable=/opt/chef/bin/chef-client
      
    
    ================================================================================
    Error executing action `set` on resource 'system_hostname[server1]'
    ================================================================================
    
    Errno::ENOENT
    -------------
    execute[run hostname] (/var/chef/cache/cookbooks/system/providers/hostname.rb line 266) had an error: Errno::ENOENT: No such file or directory - hostname
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/system/providers/hostname.rb:269:in `block (3 levels) in class_from_file'
    /var/chef/cache/cookbooks/system/providers/hostname.rb:270:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/local-node/recipes/system.rb
    
      7: system_hostname node['hostname'] do
      8:   short_hostname node['hostname']
      9:   domain_name node['system']['domain_name']
     10:   static_hosts({})
     11: end
     12: 
     13: system_timezone node['system']['timezone']
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/local-node/recipes/system.rb:7:in `from_file'
    
    system_hostname("server1") do
      action :set
      default_guard_interpreter :default
      declared_type :system_hostname
      cookbook_name "local-node"
      recipe_name "system"
      short_hostname "server1"
      domain_name "localnet.com"
      static_hosts {}
    end
    
    System Info:
    ------------
    chef_version=13.0.118
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-client worker: ppid=33529;start=09:08:12;
    executable=/opt/chef/bin/chef-client
    

Running handlers:
  - AzureExtension::ExceptionHandler
Running handlers complete
Chef Client failed. 0 resources updated in 11 seconds
```

**Comment by edupo** [comment]
We found the problem.

Not related to this cookbook.

Closing.
